---
# handlers file for ansible-xwiki-tomcat
# service does not work with tomcat
- name: stop tomcat
  become: true
  ignore_errors: yes
  command: "/etc/init.d/tomcat7 stop"

- name: start tomcat
  become: true
  ignore_errors: yes
  command: "/etc/init.d/tomcat7 start"
